name: iphone_has_notch
description: Returns true if the phone is iPhone and it has notch, returns false otherwise.
version: 1.0.0
homepage: https://github.com/awaik/iphone_has_notch

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
