name: iphone_has_notch
description: Returns true if the phone is iPhone and it has notch, returns false otherwise.
version: 0.0.1+1
homepage: https://github.com/awaik/iphone_has_notch

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
